#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm run format
npm run test
npx tsc

# if dist removed, build it
if [ ! -d "dist" ]; then
  npm run build:production
else
  echo "dist folder exists"
  rm -r dist
  npm run build:production
fi

# add all files to git
git add .

